run:
  mode: zeroshot
  seed: 42
  device: cuda
  use_wandb: false
  project: clip_proj
  exp_name: zshot_flowers_tiny
data:
  dataset: flowers102
  root: ./data/flowers102
  batch_size: 128       
  num_workers: 2
  img_size: 224
  limit_per_class: 5     
  class_limit: 20    
model:
  name: ViT-B-32
  pretrained: laion2B-s34B-b79K
  prompt_templates: ["a photo of a {class}."]
  prompt_ensemble: false
eval:
  attacks: ["none", "text_overlay"]   
  severities: [0, 3, 5]             
  max_batches: 5                     
  save_figs: true
  save_tables: true