run:
  mode: zeroshot
  seed: 42
  device: cuda
  use_wandb: false
  project: clip_proj
  exp_name: zshot_flowers
data:
  dataset: flowers102
  root: ./data/flowers102
  batch_size: 64
  num_workers: 4
  img_size: 224
model:
  name: ViT-B-32
  pretrained: laion2B-s34B-b79K
  prompt_templates: ["a photo of a {class}."]
  prompt_ensemble: false
eval:
  attacks: ["none", "text_overlay", "gaussian_noise", "gaussian_blur", "lowres"]
  severities: [0,1,2,3,4,5]
  save_figs: true
  save_tables: true
