run:
  mode: fewshot
  seed: 42
  device: cuda
  use_wandb: false
  project: clip_proj
  exp_name: coop_flowers_tiny
data:
  dataset: flowers102
  root: ./data/flowers102
  batch_size: 64
  num_workers: 2
  img_size: 224
  limit_per_class: 5
  class_limit: 20
model:
  name: ViT-B-32
  pretrained: laion2B-s34B-b79K
  prompt_templates: ["a photo of a {class}."]
  prompt_ensemble: false
method:
  name: coop
  k_shot: 4
  n_ctx: 8
  lr: 1e-3
  epochs: 5         
  patience: 2
eval:
  attacks: ["none","text_overlay"]
  severities: [0,3,5]
  max_batches: 5
  save_figs: true
  save_tables: true
