run:
  mode: fewshot
  seed: 42
  device: cuda
  use_wandb: false
  project: clip_proj
  exp_name: tipadapter_flowers_k4
data:
  dataset: flowers102
  root: ./data/flowers102
  batch_size: 64
  num_workers: 4
  img_size: 224
model:
  name: ViT-B-32
  pretrained: laion2B-s34B-b79K
  prompt_templates: [
    "a photo of a {class}.",
    "a blurry photo of a {class}.",
    "a black and white photo of a {class}.",
    "a close-up photo of a {class}.",
    "a bright photo of a {class}.",
    ]
method:
  name: tipadapter
  k_shot: 4
  alpha: 0.5
  beta: 5.0
  fine: false
eval:
  attacks: ["none", "text_overlay", "gaussian_noise", "gaussian_blur", "lowres"]
  severities: [0,1,2,3,4,5]
  save_tables: true